# Generated by Django 6.0.1 on 2026-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
